One_or_more_parameters_required_is_missing_in_the_header_error_code: 3111
One_or_more_parameters_is_invalid_in_the_header_error_code: 3112
Required_parameter_is_missing_in_the_URL_error_code: 3113
One_or_more_parameters_required_is_missing_in_the_header_error_message: is required in the request header
One_or_more_parameters_is_invalid_in_the_header_error_message: Invalid {0} value provided in the request header
Required_parameter_is_missing_in_the_URL_error_message: is required in the URL parameter